baseURL = "http://example.org/"
languageCode = "en-us"
title = "syd the banjo kid"

[[params.mainMenu]]
    link = '/'
    text = 'who'

[[params.mainMenu]]
    link = '/posts'
    text = 'posts'

[[params.mainMenu]]
    link = '/gallery'
    text = 'gallery'