publishDir="docs"
baseURL = "https://banjoboy.net/"
languageCode = "en-us"
title = "syd the kid"

[markup.goldmark.renderer]
unsafe= true

[[params.mainMenu]]
    link = '/'
    text = 'syd'

[[params.mainMenu]]
    link = '/thoughts'
    text = 'thinks'

[[params.mainMenu]]
    link = '/playlists'
    text = 'listens'

[[params.mainMenu]]
    link = '/about'
    text = 'is'