publishDir="docs"
baseURL = "https://banjoboy.net/"
languageCode = "en-us"
title = "syd the kid"

[[params.mainMenu]]
    link = '/about'
    text = 'syd'

[[params.mainMenu]]
    link = '/thoughts'
    text = 'thinks'

[[params.mainMenu]]
    link = '/playlists'
    text = 'listens'

[[params.mainMenu]]
    link = '/gallery'
    text = 'sees'

[[params.mainMenu]]
    link = '/'
    text = 'home'